### ISSUE TITLE
add the basic files

### ISSUE THREAD

**Issue by aindrajaya** [aindrajaya/react-tailwind-webpack#1]
## Todo
 - [x] add the html file on the public folder
 - [x] add the index.js file to call the React library
 - [x] add the index.css file to call the css properties for styling the react app
 - [x] add the App.js for the first react component integration
